spring:
    jpa:
        #database: MYSQL
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        generate-ddl: true
    hibernate:
        ddl-auto: create
    datasource:
        url: jdbc:mysql://localhost:3306/invoice_db
        username: root
        password: 1234
        driver-class-name: com.mysql.jdbc.Driver



server:
    port: 8082
