eureka:
  instance:
    appGroupName: invoices
  client:
    enabled: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
    application:
      name: invoices
    jpa:
        #database: MYSQL
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        generate-ddl: true
    hibernate:
        ddl-auto: create
    datasource:
        url: jdbc:mysql://localhost:3306/invoice_db
        username: root
        password: 1234
        driver-class-name: com.mysql.jdbc.Driver

security.basic.enable: false

server:
    port: 8082
